import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Art of CSE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section id="intro">
        <div class="grid place-items-center pt-10 bg-gradient-to-r from-cyan-500 to-green-200">
          <div>
            <h2 class="text-white text-xl font-light tracking-widest font-serif">
              SPIRIT OF INNOVATION
            </h2>
          </div>

          <div class="topbar_text_slider pt-8">
            <ul class="bxslider text">
              <li class="text-5xl text-white font-bold">
                We Love <span class="text-black">Creativity</span>
              </li>
            </ul>
          </div>

          <div class="pt-12 pb-5">
            <p class="text-gray-100">Start learning with Art of CSE</p>
          </div>
        </div>
      </section>
    </>
  );
}
